### ISSUE TITLE
Images are not created in folder

### ISSUE THREAD

**Issue by alexandrcook** [izica/php-progressive-images-webp-jp2-jxr#1]
Hello!

I am trying to convert images with your library. My code example:  

public function test()
    {

        $obData = \Izica\ProgressiveImages::fromFileSource('/images/test/avis.jpg')
            ->setFileName('testfile')
            ->setDestinationFolder($_SERVER['DOCUMENT_ROOT'] . '/images/1/')
            ->convert();

        dump($_SERVER['DOCUMENT_ROOT']);

        dump($obData);
        dump($obData->webp);
        dump(request()->file($obData->webp));
        dump(request()->file($_SERVER['DOCUMENT_ROOT'].$obData->webp));

        phpinfo();
        dd('end');
    }

I see that folder is created but there are not any files in folder. Also I didn't see any errors
I installed your library by composer to Laravel Framework 6.18.19

imagemagick, webp and jxrlib was installed by homebrew

I tried some other way of creation - like
_**convert public/images/test/avis.jpg  public/images/new/test.jp2**_ 
command in terminal and it works good - files are created

But I definitely will be glad to use your library. Will be happy for any advices!

**Comment by izica** [comment]
Hello!

I tried using it in my laravel project and the library worked fine.

This is my code in controller:
```php
public function index(){
        $sFilename = Image::whereId(44)->first()->path;

        $arData = \Izica\ProgressiveImages::fromFileSource(Storage::disk('images')->path($sFilename))
            ->setFileName('filename')
            ->setDestinationFolder($_SERVER['DOCUMENT_ROOT'] . '/images-cached/')
            ->convert()
            ->toArray();

        return ApiResponse::success([
            'image' => $arData,
        ]);
}
```

Data from response
```
        /*
            "webp": "/images-cached/filename.webp",
            "jpeg2000": "/images-cached/filename.jp2",
            "jpegxr": "/images-cached/filename.jxr"
         */
```

Please check debug of your filepath in fromFileSource(),
Make sure the destination folder exists and your web server has permissions to create files in the destination folder.

**Comment by alexandrcook** [comment]
Thank you a lot for your answer
I made some progress with finding why it doesn't work for me
There are some errors in apache.log file

**sh: convert: command not found
sh: convert: command not found
sh: convert: command not found
sh: JxrEncApp: command not found
rm: /.../images/1/testfile.tif: No such file or directory**

Don't understood why it failed with **_convert_** command - this command works properly from terminal

By the way I still getting 'right' array values like
array:4 [▼
  "source" => "/images/test/avis.jpg"
  "webp" => "/images/1/testfile.webp"
  "jpeg2000" => "/images/1/testfile.jp2"
  "jpegxr" => "/images/1/testfile.jxr"
]
even with apache's error.

**Comment by alexandrcook** [comment]
Ok, sorry! 
Seems error was because of my environment settings.
